[package]
name = "idsm"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"
serde_json = "1.0"
getopts = "0.2"
log = "0.4.22"
env_logger = "0.11.6"

[[bin]]
name = "idsd"
path = "src/main.rs"

[[bin]]
name = "packet_gen"
path = "src/packet_gen_main.rs"
